### ISSUE TITLE
Included i18n examples will not work as expected

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg-examples#1]
Originally reported by @aduth at https://github.com/nylen/gutenberg-examples/issues/9

---

Reported at: https://github.com/Automattic/jetpack/pull/7597#discussion_r131511715

Example: https://github.com/nylen/gutenberg-examples/blob/6e369f8/01-basic/block.js#L20

The `wp.i18n.__` function does not accept a domain (second parameter). i18n domain has yet to be implemented for these functions, and is still up in the air whether this is to be performed as part of the runtime call or during a build step.

See also: https://github.com/WordPress/gutenberg/tree/master/i18n

**Comment by mattyrob** [comment]
It looks like this was fixed upstream with:
https://github.com/WordPress/gutenberg/pull/5235
