### ISSUE TITLE
wordpress.org tutorial reference

### ISSUE THREAD

**Issue by llogan382** [WordPress/gutenberg-examples#116]
On https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/ , the instructions for activating Javascript don't work with the dev dependencies in package.json

It needs to be changed to this to work:

  "devDependencies": {
    "@wordpress/scripts": "6.0.0"
  },

**Comment by ajitbohra** [comment]
kindly share more details

**Comment by ryanwelcher** [comment]
I'm going to close this due to of lack of further details. Please feel free to reopen if needed.
