### ISSUE TITLE
Use the Block Type Metadata (block.json) for the examples

### ISSUE THREAD

**Issue by erikjoling** [WordPress/gutenberg-examples#121]
I'm not exactly sure how to implement Block Type Metadata of the new Block API Updates of WP 5.5: https://make.wordpress.org/core/2020/07/30/block-api-updates-in-5-5/

I would like to see (one of) the gutenberg examples in this repo use this new approach.

**Comment by ryanwelcher** [comment]
Hello and thanks for opening this issue. There are now two blocks that used the `block.json` approach in the repo and a concerted effort to update the rest. Please refer to #152 for the current status of each example.
