### ISSUE TITLE
Which one is pre-build zip archive?

### ISSUE THREAD

**Issue by kikidesignnet** [WordPress/gutenberg-examples#129]
> **Download a pre-built zip archive of the latest release.**
> Do not download from the "Clone or download" GitHub button, as this includes the source material only. Read the Development instructions below if you’re interested in building your own copy of the plugin.

This is what I see before clicking on the link to download the files. However, what I see is this:
<img width="1023" alt="Screen Shot 2021-03-11 at 9 48 23 AM" src="https://user-images.githubusercontent.com/5368455/110814362-fedeb400-824e-11eb-9519-4f2a0cccd6d2.png">

I download both the **gutenburg-examples.zip** and **source code** in order to look at both folders. The **source code** has package.json, etc that the **gutenburg-examples.zip** doesn't have. 

I'm trying to follow the block tutorial from develop.wordpress.org: https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/writing-your-first-block-type/

So which one should I be using to edit as I follow the block tutorial?

**Comment by ryanwelcher** [comment]
Hello @kikidesignnet and sorry for the late follow-up on this!

If you're wanting to edit and make changes to the blocks, you can either clone this repository or download one of the Source code options in your screenshot. The `gutenberg-examples.zip` is a version that only contains the built files and is meant to be installed as a plugin in WordPress to play around with the blocks in the block editor.
