### ISSUE TITLE
Update the code examples of Block Editor Handbook

### ISSUE THREAD

**Issue by mipon** [WordPress/gutenberg-examples#185]
The examples of [the tutorial section of Block Editor Handbook ](https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/)seems outdated, which links to this repository as the models of tutorial examples. 

> To follow along with this tutorial, you can [download the accompanying WordPress plugin](https://github.com/WordPress/gutenberg-examples) which includes all of the examples for you to try on your own site. At each step along the way, experiment by modifying the examples with your own ideas, and observe the effects they have on the block’s behavior.

Going on reading the tutorials there barely helps observe and analyze the examples of this repository at the moment, which isn't beginner-friendly and fails to serve as a starting point for beginners.

**Comment by ryanwelcher** [comment]
Thanks for opening this issue! I can definitely have a look at how the repo and docs are working together. In the meantime can you clarify what you mean by:

> Going on reading the tutorials there barely helps observe and analyze the examples of this repository at the moment, which isn't beginner-friendly and fails to serve as a starting point for beginners.

Do you mean that this repo is not beginner-friendly and if so, what do you think should be added to get it there?

**Comment by ryanwelcher** [comment]
There has been no movement on this issue. I'm going to close it but if feel free to reopen if you have more information to add.
