### ISSUE TITLE
Example 5 esnext is throwing invariant violation 152

### ISSUE THREAD

**Issue by maxxwv** [WordPress/gutenberg-examples#19]
I updated the Editable instances to RichText as this has been implemented as of 2.2.0, but other than that everything is the same as the repo code. However, I'm getting a React 152 error:

```
t(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```

**Comment by youknowriad** [comment]
you're probably rendering something that doesn't exist. Check that all the components you're rendering (RichText...) are not undefined

**Comment by maxxwv** [comment]
Sorry - it was a typo on my part. I used curly braces instead of parenthesis for the render attribute in the MediaUpload component call and didn't notice until now. Thanks for taking a look - I'm going to close this issue.
