### ISSUE TITLE
Document each example with a README.md

### ISSUE THREAD

**Issue by salcode** [WordPress/gutenberg-examples#202]
@Pixelrobin already opened PR #52 (which adds README.md files for 01 through 05) but that appears to have stalled out.

I wanted to create this issue to confirm the maintainers are in favor of adding these files.

As a sidenote: I suspect if we open a smaller PR to add a README.md to just `01-basic-esnext` as a starting point, it will be easier to address any issues and get it merged.

**Comment by metalandcoffee** [comment]
> As a sidenote: I suspect if we open a smaller PR to add a README.md to just 01-basic-esnext as a starting point, it will be easier to address any issues and get it merged.

I definitely agree with this. The first PR for to add a README.md to an example block should set the standard and wording and then future README.md PRs should try to model the first one for consistency 👍

**Comment by salcode** [comment]
On my first pass I overlooked #45, which already covers this.

Closing this duplicate issue.
