### ISSUE TITLE
Facing some JS issue

### ISSUE THREAD

**Issue by sanketio** [WordPress/gutenberg-examples#21]
Hello,

I'm facing some JS issue for below examples:

1. 03-editable
2. 03-editable-esnext
3. 04-controls
4. 04-controls-esnext
5. 05-recipe-card-esnext

![example__editable___ _gutenbergtest_ _wordpress](https://user-images.githubusercontent.com/7807348/37902919-a4a1032e-3113-11e8-9a13-c4dd5192184f.png)

As you can see in above screenshot, I'm not able to find **Example: Editable** block ( and similar for other blocks above ) because of the JS error.

When I comment https://github.com/WordPress/gutenberg-examples/blob/master/03-editable/block.js#L11 ( and similar line in the code for other examples ), **Example: Editable** block is searchable and also the JS error for **03-editable** is gone. Please check below screenshot:

![example__editable___ _gutenbergtest_ _wordpress](https://user-images.githubusercontent.com/7807348/37902859-733c5f22-3113-11e8-8b3a-75fecc6c63f3.png)

Let me know if this issue is valid or anything I missed.

**Comment by sr4136** [comment]
Same issue here with Gutenberg 2.4.0. Reverted to 2.3.0 and it worked just fine.
