### ISSUE TITLE
"register_block_script_handle was called incorrectly" notice being thrown

### ISSUE THREAD

**Issue by salcode** [WordPress/gutenberg-examples#215]
I'm seeing this notice (e.g. on on the Dashboard)

> Notice: register_block_script_handle was called incorrectly. The asset file for the "editorScript" defined in "myguten/meta-block" block definition is missing. Please see [Debugging in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) for more information. (This message was added in version 5.5.0.) in /var/www/html/wp-includes/functions.php on line 5768

![image](https://user-images.githubusercontent.com/5194588/166061138-ad947094-c3fd-4bbe-83dc-73dbb2a7fee3.png)

**Comment by ryanwelcher** [comment]
@salcode this repo has been updated recently, is this still an issue?

**Comment by salcode** [comment]
I no longer see this issue on the dashboard when using the latest version of `trunk` 👍
