### ISSUE TITLE
2 Editable examples not working (step 3 and 4)

### ISSUE THREAD

**Issue by katerlouis** [WordPress/gutenberg-examples#22]
Examples 3 and 4 are broken on my naked / Gutenberg only latest wordpress environment.

Wordpress Version: 4.9.6
Gutenberg Version: 2.9.2
Gutenberg Examples Version: 0.1.0

![image](https://user-images.githubusercontent.com/1983382/40745300-62941fbc-6457-11e8-84e4-0cd09ae97fb4.png)

**Comment by iandunn** [comment]
Possibly related #25

**Comment by skorasaurus** [comment]
I think this is fixed in https://github.com/WordPress/gutenberg-examples/pull/23

**Comment by ryancwalsh** [comment]
I've spent hours on this and agree: I can't get examples 03 or 04 to work. This is my first experience with Gutenberg, and it has been driving me crazy.

I did this: `svn export https://github.com/WordPress/gutenberg-examples/trunk/ gutenberg-examples`, so I know I have the right code.

The error in the console is:

```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Sg (react-dom.min.82e21c65.js:142)
    at m (react-dom.min.82e21c65.js:12)
    at ed (react-dom.min.82e21c65.js:65)
    at react-dom.min.82e21c65.js:87
    at rd (react-dom.min.82e21c65.js:91)
    at O (react-dom.min.82e21c65.js:90)
    at yh (react-dom.min.82e21c65.js:96)
    at lg (react-dom.min.82e21c65.js:120)
    at mg (react-dom.min.82e21c65.js:120)
    at gc (react-dom.min.82e21c65.js:127)
bg @ react-dom.min.82e21c65.js:110
d.function.d.componentDidCatch.c.callback @ react-dom.min.82e21c65.js:116
Jf @ react-dom.min.82e21c65.js:73
Kf @ react-dom.min.82e21c65.js:74
jc @ react-dom.min.82e21c65.js:134
gc @ react-dom.min.82e21c65.js:127
vb @ react-dom.min.82e21c65.js:126
ub @ react-dom.min.82e21c65.js:126
wg @ react-dom.min.82e21c65.js:137
Ze @ react-dom.min.82e21c65.js:41

```

Is there a way for me to benefit from https://github.com/WordPress/gutenberg-examples/pull/23 before it's officially accepted?

Thanks.

**Comment by ajitbohra** [comment]
@ryancwalsh you can clone the fork https://github.com/ajitbohra/gutenberg-examples for time being
