### ISSUE TITLE
Please update the Docs on developer.wordpress.org

### ISSUE THREAD

**Issue by bystrzan** [WordPress/gutenberg-examples#226]
On page [https://developer.wordpress.org/block-editor/how-to-guides/format-api/](https://developer.wordpress.org/block-editor/how-to-guides/format-api/) the link "complete format-api example" is pointing to 404: 
Should point to: [https://github.com/WordPress/gutenberg-examples/tree/trunk/non-block-examples/format-api](https://github.com/WordPress/gutenberg-examples/tree/trunk/non-block-examples/format-api)

**Comment by AndrewJDFerguson** [comment]
Same for "(optional) Review the [finished app](https://github.com/WordPress/gutenberg-examples/tree/trunk/09-code-data-basics-esnext) in the gutenberg-examples repository" link https://github.com/WordPress/gutenberg-examples/tree/trunk/09-code-data-basics-esnext on the [https://developer.wordpress.org/block-editor/how-to-guides/data-basics/5-adding-a-delete-button/](https://developer.wordpress.org/block-editor/how-to-guides/data-basics/5-adding-a-delete-button/) page.

Seems the repository was restructured without reviewing developer.wordpress content. Not sure, but it also appears that the content in the repository is not the finished app as indicated in the link text.

**Comment by dgwyer** [comment]
> Seems the repository was restructured without reviewing developer.wordpress content. Not sure, but it also appears that the content in the repository is not the finished app as indicated in the link text.

I noticed this to, today. Looks like the Gutenberg examples repo app is incomplete?

cc @adamziel

**Comment by adamziel** [comment]
Thank you for the ping! I will adjust the [data basics](https://developer.wordpress.org/block-editor/how-to-guides/data-basics/) tutorial accordingly. As for the other resources, let's loop in @ryanwelcher who might have some thoughts. 

To assess the impact, I grepped the gutenberg repository as follows:

```
; git grep gutenberg-examples | awk -F':' '{print $1}' | uniq
```

And found the following files have references to the `gutenberg-examples` repo:

```
changelog.txt
docs/how-to-guides/block-tutorial/README.md
docs/how-to-guides/block-tutorial/applying-styles-with-stylesheets.md
docs/how-to-guides/block-tutorial/block-controls-toolbar-and-sidebar.md
docs/how-to-guides/block-tutorial/block-supports-in-dynamic-blocks.md
docs/how-to-guides/block-tutorial/block-supports-in-static-blocks.md
docs/how-to-guides/block-tutorial/creating-dynamic-blocks.md
docs/how-to-guides/block-tutorial/introducing-attributes-and-editable-fields.md
docs/how-to-guides/block-tutorial/nested-blocks-inner-blocks.md
docs/how-to-guides/block-tutorial/writing-your-first-block-type.md
docs/how-to-guides/data-basics/1-data-basics-setup.md
docs/how-to-guides/data-basics/2-building-a-list-of-pages.md
docs/how-to-guides/data-basics/3-building-an-edit-form.md
docs/how-to-guides/data-basics/4-building-a-create-page-form.md
docs/how-to-guides/data-basics/5-adding-a-delete-button.md
docs/how-to-guides/data-basics/README.md
docs/how-to-guides/format-api.md
docs/how-to-guides/javascript/js-build-setup.md
docs/how-to-guides/metabox.md
docs/how-to-guides/platform/README.md
docs/how-to-guides/plugin-sidebar-0.md
```

**Comment by ryanwelcher** [comment]
Thanks @adamziel  - I'll work on getting those updated!

**Comment by dgwyer** [comment]
@adamziel @ryanwelcher Once the updates to the tutorial and code in the Gutenber examples repo have been completed do you want me to proof read the tutorial (and check repos code works as expected)?

I was already part way through when I noticed some typos etc. I'd be more than happy to go through it again from start to finish.

BTW - Thanks for the tutorial Adam. Would love to see more advanced Gutenberg articles like this! :)

**Comment by dgwyer** [comment]
@adamziel @ryanwelcher Or, if you preferred, I could go ahead and do this right away. i.e. review the tutorial and compile a working version of the code to (re) add to the repo? I'd quite like to do this anyway (would be a good learning experience) so please let me know so I can get started. Looking forward to contributing. :)

**Comment by bystrzan** [comment]
@adamziel @ryanwelcher @dgwyer - Cool You found my feedback usefull. I have some more feedback, but I'll give it to You later as for now have no time to make it happen.

**Comment by dgwyer** [comment]
@bystrzan Yes please. Any feedback would be most useful. Even if you could just post a few comments here.

**Comment by dgwyer** [comment]
@bystrzan Yes please. Any feedback would be most useful. Even if you could just post a few comments here.

**Comment by dgwyer** [comment]
Update: Today I updated the how-to guide docs and the repo code in Gutenberg examples (as part of our company's FFTF contribution day).

https://github.com/WordPress/gutenberg-examples/pull/227
https://github.com/WordPress/gutenberg/pull/43633

**Comment by adamziel** [comment]
This is super helpful @dgwyer, thank you so much!

**Comment by ryanwelcher** [comment]
This looks to be addressed. I'm going to close.  if there are any further issues, please open a new issue.
