### ISSUE TITLE
Missing dependency in gutenberg-examples/blocks-non-jsx/01-basic/block.asset.php

### ISSUE THREAD

**Issue by nedkelly** [WordPress/gutenberg-examples#238]
Hey, these examples are really helpful, thanks for your efforts.

I tried setting up the basic non-jsx example but kept getting a console error `Uncaught TypeError: Cannot read properties of undefined (reading 'useBlockProps')`, I noticed that the block.asset.php file was missing the `wp-block-editor` dependency so I added it and the block began working.

```php
<?php return array('dependencies' => array('wp-blocks', 'wp-element', 'wp-i18n', 'wp-block-editor'), 'version' => 'a35cc1c098b69994c9c6d6dc1416bb90');
```

Cheers.

**Comment by ryanwelcher** [comment]
This was fixed with #240
