### ISSUE TITLE
Float/Clear issue with Recipe Card Example

### ISSUE THREAD

**Issue by Alx101** [WordPress/gutenberg-examples#24]
**Issue:**
`float: right` on recipe-image element causes block to spill out of container and overlap content below.
![image](https://user-images.githubusercontent.com/6023440/41911100-fc7210e0-794b-11e8-8676-10e20110a87f.png)

**Solution**
Apply clearfix css to container div:
`
.wp-block-gutenberg-examples-example-05-recipe-card:after {
    content:"";
    clear:both;
    display: table;
}
`
![image](https://user-images.githubusercontent.com/6023440/41911207-56260e98-794c-11e8-8215-8f040a7ffd4a.png)

**Comment by ajitbohra** [comment]
Fixed here e5aedd0f0a50cb6dcb21825aea3494211e6e4833
