### ISSUE TITLE
Include examples of tests

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg-examples#26]
I've found it time consuming to get Jest properly configured with Babel and JSX and all the things. I think it'd be useful to include working testings and all the required build tool configs, in order to make this easier and more convenient for people.

**Comment by iandunn** [comment]
`wp-scripts` probably makes this easier, but [the docs] (https://github.com/WordPress/gutenberg/tree/master/packages/scripts) only talk about how to install the script, and don't have any examples of actual tests.

**Comment by iandunn** [comment]
Related https://github.com/wp-cli/ideas/issues/103

**Comment by swissspidy** [comment]
This is still relevant.

I am having trouble getting Jest to run with wp-scripts, see today's discussion on Slack: https://wordpress.slack.com/archives/C02QB2JS7/p1556031641343900.

**Comment by iandunn** [comment]
I started a repo in order to try and get a minimal example working.

https://github.com/iandunn/wp-scripts-test-example

I forked https://github.com/eventespresso/event-espresso-core (props @nerrad) and started removing everything that wasn't absolutely necessary for unit tests. it'd be nice to add e2e as well, but so far i've only had time for unit.

It's working, but still requires a lot of stuff that seems like `wp-scripts` should take care of automatically. I ran out of time to experiment more, though.

cc @gziolo in case you have any insight into what (if anything) `wp-scripts` can handle, and what still needs work upsteam.

**Comment by gziolo** [comment]
Now that I nearly finished adding support for `lint-js`, I will try to integrate unit and e2e tests into this repository. 

I hope I can identify all the issues we have at the moment when working outside of Gutenberg. I anticipate we might want to be more strict about pattern matching for both types of tests. This should make documenting easier and further usage less confusing.

**Comment by iandunn** [comment]
That would be extremely helpful, thank you!

**Comment by iandunn** [comment]
As another example for people, @ryelle got unit tests working for WordCamp.org in https://github.com/WordPress/wordcamp.org/pull/211.

**Comment by gziolo** [comment]
I opened https://github.com/WordPress/gutenberg-examples/pull/84 to perform my own explorations and identified a few places where we can improve WordPress packages to make it more seamless.

**Comment by gziolo** [comment]
Tests are located in:
https://github.com/WordPress/gutenberg-examples/tree/trunk/test

It had some further iterations and it works well now.
