### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by Jayce53** [WordPress/gutenberg-examples#30]
In 03-editable and 04-controls, _blocks.source_ is undefined:

```
( function( blocks, i18n, element ) {
	var el = element.createElement;
	var __ = i18n.__;
	var RichText = blocks.RichText;
	var children = blocks.source.children;

```

WP version 4.9.8RC2
Gutenberg examples: 3564e388
Gutenberg: 767ef1e3

**Comment by ajitbohra** [comment]
@Jayce53 

`blocks.source` is deprecated

examples are not in sync with the latest Gutenberg changes currently it's being updated here #23
