### ISSUE TITLE
Add Readme.md file for each block

### ISSUE THREAD

**Issue by ajitbohra** [WordPress/gutenberg-examples#45]
- [ ] Short description about the block
- [ ] Screenshot for block frontend and backend
- [ ] Quick link to components / packages used in example

**Comment by Pixelrobin** [comment]
Added PR: https://github.com/WordPress/gutenberg-examples/pull/52

**Comment by metalandcoffee** [comment]
Hi @ryanwelcher! I almost have a PR ready for the first block's README.md. Just wanted to confirm that you would like me to open a PR against the `trunk` branch?

**Comment by metalandcoffee** [comment]
Would someone mind assigning this ticket to me? Thank you 😀

**Comment by metalandcoffee** [comment]
Hi again! Just now seeing that @salcode already has a PR for it so looks like it's already taken care of so I will scrap what I have. Let me know if I can help in any other way 👍

**Comment by lgedeon** [comment]
@metalandcoffee Did your PR have additional information that could help expand what @salcode was doing? Or could you review and approve that PR so that it can be merged? It seems to have stalled out for some reason. Maybe a little help from you could push it to the finish line?

**Comment by ryanwelcher** [comment]
Closing this in favor of the work being done to move these examples to https://github.com/wptrainingteam/wp-block-development-examples

**Comment by sinanisler** [comment]
this is a good idea I like it
