### ISSUE TITLE
in 05-recipe-card (and esnext version) post edit whitescreen

### ISSUE THREAD

**Issue by tharsheblows** [WordPress/gutenberg-examples#5]
To reproduce:

1. make a post with the recipe card (either version) and save it
2. go to post in posts list and try to edit with Gutenberg

This whitescreens for me with the error:
```
react.3a8927d9.js:343 Uncaught Error: Objects are not valid as a React child (found: object with keys {type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
    in ul
    in div 
    ....
```

Taking out the multiline props fixes this, although admittedly doesn't give you a list. 😊 I'm not sure if the issues is here or in Gutenberg or if something's changed recently. (I wanted to raise an issue before I forgot the details!)

**Comment by aduth** [comment]
Thanks for raising! I noticed this myself in my last round of testing. There were quite a few issues in the recipe blocks. They should be in a fairly good state now as of e4023ec2475f3c7e5fcaca3adb9382ba0a97764d.
