### ISSUE TITLE
Recipe Card examples encounter error

### ISSUE THREAD

**Issue by mor10** [WordPress/gutenberg-examples#64]
Both `Example: Recipe Card` and `Example: Recipe Card (esnext)` generate the following error:

> This block has encountered an error and cannot be previewed.

I have not had time to debug the issue.

**Comment by iandunn** [comment]
What it an existing block that broke because of a recent change, or a new block?

I just tried with a new block and it worked for me, so I'm wondering if some syntax changed without a `transform` or something.

**Comment by ryanwelcher** [comment]
@mor10 just following up on this. All the blocks have been updated, is this still an issue?

**Comment by ryanwelcher** [comment]
I'm going to close this due to inactivity but if this is still an issue, please feel free to reopen.
