### ISSUE TITLE
Use SASS in ESNext examples

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg-examples#66]
That would provide an example that is modern and consistent with standard block development practices.

The minified output should probably be `build/style.css` rather than `/style.css`.

**Comment by iandunn** [comment]
This is probably blocked until https://github.com/WordPress/gutenberg/issues/14801 is resolved

**Comment by ryanwelcher** [comment]
Since this ticket was created, the majority of the blocks are now using `.scss` files. I'm going to close this out but please feel  free to re-open if it has not been resolved.
