### ISSUE TITLE
post data example

### ISSUE THREAD

**Issue by michellomp** [WordPress/gutenberg-examples#7]
Hi Andrew thanks for this examples but I wonder if you consider adding more examples in the future like posts block. There's latest post block in gutenberg and I try to do a similar block but I can't find a way to import a function from another files like it's done in latest post block
```
var el = wp.element.createElement,
registerBlockType = wp.blocks.registerBlockType,
import { getData } from './data.js';
```
When I add import getdata my block disappear in the editor and I can't understand why.

**Comment by youknowriad** [comment]
import refers to the `ES6` modules features. If you'd like to use ES6 modules, you'll have to use a module bundler (webpack for example). You can take a look at the [`ESnext` examples](https://github.com/WordPress/gutenberg-examples/tree/master/01-basic-esnext) where you can use ES6 modules. There's already the right `webpack` config there.

**Comment by michellomp** [comment]
@youknowriad  Thanks a lot Riad
