### ISSUE TITLE
`npm start` is missing from package.json

### ISSUE THREAD

**Issue by rickcurran** [WordPress/gutenberg-examples#86]
The Readme file states:

> To build a development version of the plugin and watch changes for automatic rebuild
> 
> `npm start`

But there is no 'start' script configured in the `scripts` section of the package.json file. The result is that it is not possible to run `npm start`, it results in an error: `npm ERR! missing script: start`

Is this a documentation error or is the `start` script actually missing?

**Comment by mathiasmadsen** [comment]
I had the same issue. I believe the documentation is missing a clarification. It should say:

> To build a development version of **each block** and watch changes for automatic rebuild
`npm start`

**Comment by rickcurran** [comment]
@mathiasmadsen Ah yep, I think that's right. `nom start` is available for each block individually but not at the top level.
