### ISSUE TITLE
Questions: include and plugin_dir_path

### ISSUE THREAD

**Issue by mahnunchik** [WordPress/gutenberg-examples#97]
Hi, I have some questions about main file of the plugin.

```php
include '01-basic/index.php';
```

1. Why do you use `include` instead of `require_once`?
2. Why don't you use recommended `plugin_dir_path ` method? https://developer.wordpress.org/plugins/plugin-basics/best-practices/

**Comment by ryanwelcher** [comment]
Hi there! We have updated the repo to use `require` and `plugin_dir_path`. Thanks for the question! I'm going to close this out but feel free to reopen if needed.
